/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Servicos24hRouteImport } from './routes/servicos-24h'
import { Route as SegurosRouteImport } from './routes/seguros'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as ConsorciosRouteImport } from './routes/consorcios'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegurosCategoryIdRouteImport } from './routes/seguros/$categoryId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Servicos24hRoute = Servicos24hRouteImport.update({
  id: '/servicos-24h',
  path: '/servicos-24h',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsorciosRoute = ConsorciosRouteImport.update({
  id: '/consorcios',
  path: '/consorcios',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosCategoryIdRoute = SegurosCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => SegurosRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/consorcios': typeof ConsorciosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/financas': typeof FinancasRoute
  '/lgpd': typeof LgpdRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/saude': typeof SaudeRoute
  '/seguros': typeof SegurosRouteWithChildren
  '/servicos-24h': typeof Servicos24hRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/seguros/$categoryId': typeof SegurosCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/consorcios': typeof ConsorciosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/financas': typeof FinancasRoute
  '/lgpd': typeof LgpdRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/saude': typeof SaudeRoute
  '/seguros': typeof SegurosRouteWithChildren
  '/servicos-24h': typeof Servicos24hRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/seguros/$categoryId': typeof SegurosCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/consorcios': typeof ConsorciosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/financas': typeof FinancasRoute
  '/lgpd': typeof LgpdRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/saude': typeof SaudeRoute
  '/seguros': typeof SegurosRouteWithChildren
  '/servicos-24h': typeof Servicos24hRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/seguros/$categoryId': typeof SegurosCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/consorcios'
    | '/fale-conosco'
    | '/financas'
    | '/lgpd'
    | '/privacidade'
    | '/quem-somos'
    | '/saude'
    | '/seguros'
    | '/servicos-24h'
    | '/sitemap.xml'
    | '/termos'
    | '/api/contact'
    | '/blog/$slug'
    | '/seguros/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/consorcios'
    | '/fale-conosco'
    | '/financas'
    | '/lgpd'
    | '/privacidade'
    | '/quem-somos'
    | '/saude'
    | '/seguros'
    | '/servicos-24h'
    | '/sitemap.xml'
    | '/termos'
    | '/api/contact'
    | '/blog/$slug'
    | '/seguros/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/consorcios'
    | '/fale-conosco'
    | '/financas'
    | '/lgpd'
    | '/privacidade'
    | '/quem-somos'
    | '/saude'
    | '/seguros'
    | '/servicos-24h'
    | '/sitemap.xml'
    | '/termos'
    | '/api/contact'
    | '/blog/$slug'
    | '/seguros/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ConsorciosRoute: typeof ConsorciosRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  FinancasRoute: typeof FinancasRoute
  LgpdRoute: typeof LgpdRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SaudeRoute: typeof SaudeRoute
  SegurosRoute: typeof SegurosRouteWithChildren
  Servicos24hRoute: typeof Servicos24hRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos-24h': {
      id: '/servicos-24h'
      path: '/servicos-24h'
      fullPath: '/servicos-24h'
      preLoaderRoute: typeof Servicos24hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consorcios': {
      id: '/consorcios'
      path: '/consorcios'
      fullPath: '/consorcios'
      preLoaderRoute: typeof ConsorciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros/$categoryId': {
      id: '/seguros/$categoryId'
      path: '/$categoryId'
      fullPath: '/seguros/$categoryId'
      preLoaderRoute: typeof SegurosCategoryIdRouteImport
      parentRoute: typeof SegurosRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface SegurosRouteChildren {
  SegurosCategoryIdRoute: typeof SegurosCategoryIdRoute
}

const SegurosRouteChildren: SegurosRouteChildren = {
  SegurosCategoryIdRoute: SegurosCategoryIdRoute,
}

const SegurosRouteWithChildren =
  SegurosRoute._addFileChildren(SegurosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ConsorciosRoute: ConsorciosRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  FinancasRoute: FinancasRoute,
  LgpdRoute: LgpdRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  SaudeRoute: SaudeRoute,
  SegurosRoute: SegurosRouteWithChildren,
  Servicos24hRoute: Servicos24hRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
