/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Servicos24hRouteImport } from './routes/servicos-24h'
import { Route as SegurosRouteImport } from './routes/seguros'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as ConsorciosRouteImport } from './routes/consorcios'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SolucoesSolucaoRouteImport } from './routes/solucoes.$solucao'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as SolucoesSolucaoIndexRouteImport } from './routes/solucoes.$solucao.index'
import { Route as SolucoesSolucaoCategoriaRouteImport } from './routes/solucoes.$solucao.$categoria'
import { Route as SolucoesSolucaoCategoriaIndexRouteImport } from './routes/solucoes.$solucao.$categoria.index'
import { Route as SolucoesSolucaoCategoriaNucleoRouteImport } from './routes/solucoes.$solucao.$categoria.$nucleo'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Servicos24hRoute = Servicos24hRouteImport.update({
  id: '/servicos-24h',
  path: '/servicos-24h',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsorciosRoute = ConsorciosRouteImport.update({
  id: '/consorcios',
  path: '/consorcios',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolucoesRoute,
} as any)
const SolucoesSolucaoRoute = SolucoesSolucaoRouteImport.update({
  id: '/$solucao',
  path: '/$solucao',
  getParentRoute: () => SolucoesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSolucaoIndexRoute = SolucoesSolucaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolucoesSolucaoRoute,
} as any)
const SolucoesSolucaoCategoriaRoute =
  SolucoesSolucaoCategoriaRouteImport.update({
    id: '/$categoria',
    path: '/$categoria',
    getParentRoute: () => SolucoesSolucaoRoute,
  } as any)
const SolucoesSolucaoCategoriaIndexRoute =
  SolucoesSolucaoCategoriaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SolucoesSolucaoCategoriaRoute,
  } as any)
const SolucoesSolucaoCategoriaNucleoRoute =
  SolucoesSolucaoCategoriaNucleoRouteImport.update({
    id: '/$nucleo',
    path: '/$nucleo',
    getParentRoute: () => SolucoesSolucaoCategoriaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/consorcios': typeof ConsorciosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/financas': typeof FinancasRoute
  '/lgpd': typeof LgpdRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/saude': typeof SaudeRoute
  '/seguros': typeof SegurosRoute
  '/servicos-24h': typeof Servicos24hRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/termos': typeof TermosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solucoes/$solucao': typeof SolucoesSolucaoRouteWithChildren
  '/solucoes/': typeof SolucoesIndexRoute
  '/solucoes/$solucao/$categoria': typeof SolucoesSolucaoCategoriaRouteWithChildren
  '/solucoes/$solucao/': typeof SolucoesSolucaoIndexRoute
  '/solucoes/$solucao/$categoria/$nucleo': typeof SolucoesSolucaoCategoriaNucleoRoute
  '/solucoes/$solucao/$categoria/': typeof SolucoesSolucaoCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/consorcios': typeof ConsorciosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/financas': typeof FinancasRoute
  '/lgpd': typeof LgpdRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/saude': typeof SaudeRoute
  '/seguros': typeof SegurosRoute
  '/servicos-24h': typeof Servicos24hRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solucoes': typeof SolucoesIndexRoute
  '/solucoes/$solucao': typeof SolucoesSolucaoIndexRoute
  '/solucoes/$solucao/$categoria/$nucleo': typeof SolucoesSolucaoCategoriaNucleoRoute
  '/solucoes/$solucao/$categoria': typeof SolucoesSolucaoCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/consorcios': typeof ConsorciosRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/financas': typeof FinancasRoute
  '/lgpd': typeof LgpdRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/saude': typeof SaudeRoute
  '/seguros': typeof SegurosRoute
  '/servicos-24h': typeof Servicos24hRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/termos': typeof TermosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solucoes/$solucao': typeof SolucoesSolucaoRouteWithChildren
  '/solucoes/': typeof SolucoesIndexRoute
  '/solucoes/$solucao/$categoria': typeof SolucoesSolucaoCategoriaRouteWithChildren
  '/solucoes/$solucao/': typeof SolucoesSolucaoIndexRoute
  '/solucoes/$solucao/$categoria/$nucleo': typeof SolucoesSolucaoCategoriaNucleoRoute
  '/solucoes/$solucao/$categoria/': typeof SolucoesSolucaoCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/consorcios'
    | '/fale-conosco'
    | '/financas'
    | '/lgpd'
    | '/privacidade'
    | '/quem-somos'
    | '/saude'
    | '/seguros'
    | '/servicos-24h'
    | '/sitemap.xml'
    | '/solucoes'
    | '/termos'
    | '/api/contact'
    | '/blog/$slug'
    | '/solucoes/$solucao'
    | '/solucoes/'
    | '/solucoes/$solucao/$categoria'
    | '/solucoes/$solucao/'
    | '/solucoes/$solucao/$categoria/$nucleo'
    | '/solucoes/$solucao/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/consorcios'
    | '/fale-conosco'
    | '/financas'
    | '/lgpd'
    | '/privacidade'
    | '/quem-somos'
    | '/saude'
    | '/seguros'
    | '/servicos-24h'
    | '/sitemap.xml'
    | '/termos'
    | '/api/contact'
    | '/blog/$slug'
    | '/solucoes'
    | '/solucoes/$solucao'
    | '/solucoes/$solucao/$categoria/$nucleo'
    | '/solucoes/$solucao/$categoria'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/consorcios'
    | '/fale-conosco'
    | '/financas'
    | '/lgpd'
    | '/privacidade'
    | '/quem-somos'
    | '/saude'
    | '/seguros'
    | '/servicos-24h'
    | '/sitemap.xml'
    | '/solucoes'
    | '/termos'
    | '/api/contact'
    | '/blog/$slug'
    | '/solucoes/$solucao'
    | '/solucoes/'
    | '/solucoes/$solucao/$categoria'
    | '/solucoes/$solucao/'
    | '/solucoes/$solucao/$categoria/$nucleo'
    | '/solucoes/$solucao/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ConsorciosRoute: typeof ConsorciosRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  FinancasRoute: typeof FinancasRoute
  LgpdRoute: typeof LgpdRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SaudeRoute: typeof SaudeRoute
  SegurosRoute: typeof SegurosRoute
  Servicos24hRoute: typeof Servicos24hRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolucoesRoute: typeof SolucoesRouteWithChildren
  TermosRoute: typeof TermosRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos-24h': {
      id: '/servicos-24h'
      path: '/servicos-24h'
      fullPath: '/servicos-24h'
      preLoaderRoute: typeof Servicos24hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consorcios': {
      id: '/consorcios'
      path: '/consorcios'
      fullPath: '/consorcios'
      preLoaderRoute: typeof ConsorciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/solucoes/$solucao': {
      id: '/solucoes/$solucao'
      path: '/$solucao'
      fullPath: '/solucoes/$solucao'
      preLoaderRoute: typeof SolucoesSolucaoRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/$solucao/': {
      id: '/solucoes/$solucao/'
      path: '/'
      fullPath: '/solucoes/$solucao/'
      preLoaderRoute: typeof SolucoesSolucaoIndexRouteImport
      parentRoute: typeof SolucoesSolucaoRoute
    }
    '/solucoes/$solucao/$categoria': {
      id: '/solucoes/$solucao/$categoria'
      path: '/$categoria'
      fullPath: '/solucoes/$solucao/$categoria'
      preLoaderRoute: typeof SolucoesSolucaoCategoriaRouteImport
      parentRoute: typeof SolucoesSolucaoRoute
    }
    '/solucoes/$solucao/$categoria/': {
      id: '/solucoes/$solucao/$categoria/'
      path: '/'
      fullPath: '/solucoes/$solucao/$categoria/'
      preLoaderRoute: typeof SolucoesSolucaoCategoriaIndexRouteImport
      parentRoute: typeof SolucoesSolucaoCategoriaRoute
    }
    '/solucoes/$solucao/$categoria/$nucleo': {
      id: '/solucoes/$solucao/$categoria/$nucleo'
      path: '/$nucleo'
      fullPath: '/solucoes/$solucao/$categoria/$nucleo'
      preLoaderRoute: typeof SolucoesSolucaoCategoriaNucleoRouteImport
      parentRoute: typeof SolucoesSolucaoCategoriaRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface SolucoesSolucaoCategoriaRouteChildren {
  SolucoesSolucaoCategoriaNucleoRoute: typeof SolucoesSolucaoCategoriaNucleoRoute
  SolucoesSolucaoCategoriaIndexRoute: typeof SolucoesSolucaoCategoriaIndexRoute
}

const SolucoesSolucaoCategoriaRouteChildren: SolucoesSolucaoCategoriaRouteChildren =
  {
    SolucoesSolucaoCategoriaNucleoRoute: SolucoesSolucaoCategoriaNucleoRoute,
    SolucoesSolucaoCategoriaIndexRoute: SolucoesSolucaoCategoriaIndexRoute,
  }

const SolucoesSolucaoCategoriaRouteWithChildren =
  SolucoesSolucaoCategoriaRoute._addFileChildren(
    SolucoesSolucaoCategoriaRouteChildren,
  )

interface SolucoesSolucaoRouteChildren {
  SolucoesSolucaoCategoriaRoute: typeof SolucoesSolucaoCategoriaRouteWithChildren
  SolucoesSolucaoIndexRoute: typeof SolucoesSolucaoIndexRoute
}

const SolucoesSolucaoRouteChildren: SolucoesSolucaoRouteChildren = {
  SolucoesSolucaoCategoriaRoute: SolucoesSolucaoCategoriaRouteWithChildren,
  SolucoesSolucaoIndexRoute: SolucoesSolucaoIndexRoute,
}

const SolucoesSolucaoRouteWithChildren = SolucoesSolucaoRoute._addFileChildren(
  SolucoesSolucaoRouteChildren,
)

interface SolucoesRouteChildren {
  SolucoesSolucaoRoute: typeof SolucoesSolucaoRouteWithChildren
  SolucoesIndexRoute: typeof SolucoesIndexRoute
}

const SolucoesRouteChildren: SolucoesRouteChildren = {
  SolucoesSolucaoRoute: SolucoesSolucaoRouteWithChildren,
  SolucoesIndexRoute: SolucoesIndexRoute,
}

const SolucoesRouteWithChildren = SolucoesRoute._addFileChildren(
  SolucoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ConsorciosRoute: ConsorciosRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  FinancasRoute: FinancasRoute,
  LgpdRoute: LgpdRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  SaudeRoute: SaudeRoute,
  SegurosRoute: SegurosRoute,
  Servicos24hRoute: Servicos24hRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolucoesRoute: SolucoesRouteWithChildren,
  TermosRoute: TermosRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
